import { motion } from "motion/react";
import { SEO } from "../components/SEO";

export default function PrivacyPolicy() {
  return (
    <div className="bg-[#0a0a0a] min-h-screen text-white/90 selection:bg-[#D4AF37] selection:text-black font-light relative overflow-hidden">
      {/* Premium Background Glow */}
      <div
        className="absolute inset-0 pointer-events-none z-0"
        style={{
          backgroundImage:
            "radial-gradient(ellipse 65% 55% at 50% 30%, rgba(212,175,55,0.06) 0%, transparent 70%)",
        }}
      />

      <SEO
        title="Privacy Policy — Ryan Kroge"
        description="Learn how we collect, use, and safeguard your personal information, caller audio, and cookie preferences on ryankroge.com."
        path="/privacy-policy"
        type="website"
      />

      {/* Hero Header */}
      <div className="relative pt-32 md:pt-48 pb-12 px-6 z-10">
        <div className="max-w-4xl mx-auto text-center md:text-left">
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <div className="flex items-center justify-center md:justify-start gap-3 mb-6">
              <div className="w-12 h-[1px] bg-[#D4AF37]" />
              <span className="text-[#D4AF37] tracking-[0.2em] text-xs uppercase font-kiona font-bold">Legal</span>
            </div>
            <h1 className="text-4xl md:text-6xl font-light mb-4 tracking-tight">
              Privacy Policy
            </h1>
            <p className="text-white/40 text-xs tracking-widest font-kiona mb-8">
              LAST UPDATED: JULY 2026
            </p>
            <div className="w-full h-[1px] bg-white/10" />
          </motion.div>
        </div>
      </div>

      {/* Document Body */}
      <div className="relative max-w-4xl mx-auto px-6 pb-24 z-10">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="article-content"
        >
          <p>
            This Privacy Policy explains how Ryan Kroge ("we," "us," or "our") collects, uses, discloses, and protects your information when you visit ryankroge.com (the "Website") or use our services, including our scheduling systems and automated telephone assistants.
          </p>

          <h2>1. Information We Collect</h2>
          <p>
            We collect information that you provide to us directly, as well as information collected automatically during your interactions with our Website:
          </p>
          <ul>
            <li>
              <strong>Contact Details:</strong> Name, email address, phone number, and any project-specific notes you submit through our contact forms.
            </li>
            <li>
              <strong>Appointment Scheduling:</strong> Requested consultation times and details entered when you book a meeting.
            </li>
            <li>
              <strong>Voice Interactions & Phone Calls:</strong> If you call our listed phone numbers or schedule an interactive call, we process caller phone numbers, call audio recordings, and speech-to-text transcripts generated by our automated assistant to answer questions and manage appointment booking.
            </li>
            <li>
              <strong>Technical & Usage Data:</strong> IP address, browser type, operating system, page views, and navigation metrics collected automatically.
            </li>
          </ul>

          <h2>2. Cookies and Tracking Technologies</h2>
          <p>
            We use cookies and similar tracking technologies to protect our forms, analyze website traffic, and remember your choices.
          </p>
          <ul>
            <li>
              <strong>CookieYes (Strictly Necessary):</strong> Stores your cookie consent selections so your preferences are preserved across multiple sessions without repeated prompts.
            </li>
            <li>
              <strong>Google Tag Manager & Google Analytics 4 (Performance & Analytics):</strong> Compiles aggregated, non-personally identifiable traffic statistics, session durations, and user flow metrics to help us optimize the Website's performance.
            </li>
            <li>
              <strong>Microsoft Clarity (Performance & Analytics):</strong> Provides heatmaps and session recording replays to help us diagnose UX errors and improve responsiveness.
            </li>
            <li>
              <strong>Google reCAPTCHA v2 (Security):</strong> Runs risk analysis checks on contact submissions to distinguish human operators from spam bots, keeping our systems secure.
            </li>
          </ul>
          <p>
            <strong>Managing Cookies:</strong> You can modify your consent settings at any time using the CookieYes consent banner at the bottom of the screen, or by configuring your web browser to block or delete cookies entirely.
          </p>

          <h2>3. Service Consolidation & Removed Pages</h2>
          <p>
            Please note that we recently simplified our website structure and removed legacy services pages. Any historical customer data previously gathered in connection with discontinued pages remains protected under the terms of this Privacy Policy and will be deleted once it is no longer required for legitimate business purposes.
          </p>

          <h2>4. Third-Party Service Providers</h2>
          <p>
            We share your information with trusted third-party service providers solely to operate our Website, secure our API endpoints, and coordinate consulting appointments:
          </p>
          <ul>
            <li>
              <strong>Supabase:</strong> Secure database hosting where contact form submissions are stored.
            </li>
            <li>
              <strong>Retell AI:</strong> Handles interactive telephone routing, call audio recording, and automated speech-to-text transcripts.
            </li>
            <li>
              <strong>Twilio:</strong> Delivers post-call SMS booking notifications and confirmation updates.
            </li>
            <li>
              <strong>Cal.com:</strong> Powers the appointment availability search and coordinates calendar slot bookings.
            </li>
          </ul>
          <p>
            We do not sell, rent, or trade your personal information to third parties for marketing or promotional campaigns.
          </p>

          <h2>5. Data Security & Retention</h2>
          <p>
            We implement appropriate technical and administrative safeguards to protect your personal data from unauthorized access or disclosure. Personal information, call recordings, and transcripts are retained only as long as necessary to fulfill the operational services outlined in this Policy or comply with legal requirements.
          </p>

          <h2>6. Contact Us</h2>
          <p>
            If you have questions, concerns, or requests regarding this Privacy Policy or your personal information, please contact us at:
          </p>
          <ul>
            <li><strong>Email:</strong> <a href="mailto:hello@ryankroge.com">hello@ryankroge.com</a></li>
            <li><strong>Location:</strong> Detroit, Michigan</li>
          </ul>
        </motion.div>
      </div>
    </div>
  );
}
